# Generated by Django 2.2.5 on 2019-09-24 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_image', models.FileField(upload_to='')),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=270)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('RT', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TwitterApp.T_user')),
            ],
        ),
    ]
