# Generated by Django 2.2.5 on 2019-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
