# Generated by Django 2.2.5 on 2019-09-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0002_auto_20190924_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='user_image',
            field=models.FileField(default='NULL', upload_to=''),
        ),
    ]
