# Generated by Django 2.2.5 on 2019-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0003_auto_20190924_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comment',
            field=models.TextField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='user_image',
            field=models.ImageField(default='NULL', upload_to='profile'),
        ),
    ]
